### ISSUE TITLE
Normalize white space in unselected inlines

### ISSUE THREAD

**Issue by aiwenar** [openstax-poland/cnx-designer#133]
See openstax-poland/adaptarr-front#566

**Comment by PiotrKozlowski** [comment]
Testing for this would be to check if spaces at the beginning and at the end of inlines are being moved outside of them

**Comment by MartaSztuka** [comment]
@PiotrKozlowski is this expected behaviour?

GIVEN Login to [base-url]
AND Draft in which you have editing permissions is open
AND Create inline e.g  Term
AND Write a phrase inside of it, leaving space at the beginning and at the end
THEN Save the draft 
AND Open ot again
THEN Spaces are outside the inline frame

![Screenshot from 2021-04-02 12-20-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fba961bb-b624-4d75-b7de-62d197f9b060)

**Comment by PiotrKozlowski** [comment]
Yes, exaclty.
```
text[  term with 3 spaces at the beginning and at the end   ]text
```

after saving and reopening:

```
text   [term with 3 spaces at the beginning and at the end]   text
```
